version: "2.2"
services:
  mysql:
    image: 'mariadb:10.3'
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dein-li-newman
      - SESSION_SECRET
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      sh -c "mysqld --default-authentication-plugin=mysql_native_password &&
             mysql -uuser -ppassword dein-li-newman < $$(pwd)/test/testdata/data_I_main.sql &&
             mysql -uuser -ppassword dein-li-newman < $$(pwd)/test/testdata/data_II_calls-get-links.sql &&
             mysql -uuser -ppassword dein-li-newman < $$(pwd)/test/testdata/data_III_calls-get-statistics.sql &&
             mysql -uuser -ppassword dein-li-newman < $$(pwd)/test/testdata/data_IV_calls-noise.sql"
    networks:
      - network
  backend:
    image: ${API_IMAGE_NAME}
    container_name: ${BACKEND_CONTAINER_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SALT_JWT=salt
      - SALT_MAIL=salt
      - API_URL=${BACKEND_CONTAINER_NAME}:3000
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=${MYSQL_CONTAINER_NAME}
      - DB_PORT=3306
      - DB_DATABASE=dein-li-newman
      - NODE_ENV=newman
      - KEYCLOAK_URL=https://account.sebamomann.de
      - KEYCLOAK_REALM=test
      - KEYCLOAK_CLIENT-ID=test
    healthcheck:
      test: ["CMD", "curl", "localhost:3000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network
  newman:
    image: postman/newman:alpine
    container_name: ${NEWMAN_CONTAINER_NAME}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - /var/www/vhosts/sebamomann.dankoe.de/testing.dein.li/dein-li-newman.postman_environment:/etc/newman/environment.json.postman_environment

networks:
  network:
    name: ${NETWORK_NAME}
    external: true
