version: "2.2"
services:
  mysql:
    image: 'mariadb:10.3'
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dein-li-newman
      - SESSION_SECRET
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks:
      - network
  backend:
    image: ${API_IMAGE}
    container_name: ${BACKEND_CONTAINER_NAME}
    depends_on:
      - mysql
    environment:
      - SALT_JWT=salt
      - SALT_MAIL=salt
      - API_URL=${BACKEND_CONTAINER_NAME}:3000
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=MYSQL_CONTAINER_NAME
      - DB_PORT=3306
      - DB_DATABASE=dein-li-newman
      - NODE_ENV=newman
      - KEYCLOAK_URL=https://account.sebamomann.de
      - KEYCLOAK_REALM=test
      - KEYCLOAK_CLIENT-ID=test
    healthcheck:
      test: ["CMD", "curl", "localhost:3000/healthcheck", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network
networks:
  network:
    name: ${NETWORK_NAME}
    external: true
