version: "2.2"
services:
  newman:
    image: postman/newman:alpine
    container_name: ${NEWMAN_CONTAINER_NAME}
    volumes:
      - /var/www/vhosts/sebamomann.dankoe.de/testing.dein.li/dein-li-newman.postman_environment:/etc/newman/environment.json.postman_environment
    networks:
      - network
networks:
  network:
    name: ${NETWORK_NAME}
    external: true
