version: "2.2"
services:
  newman:
    image: postman/newman:alpine
    container_name: ${NEWMAN_CONTAINER_NAME}
    volumes:
      - /var/www/vhosts/sebamomann.dankoe.de/testing.dein.li/dein-li-newman.postman_environment:/etc/newman/environment.json.postman_environment
    command: run "https://raw.githubusercontent.com/sebamomann/dein-li-backend/${COMMIT_HASH}/test/collection/dein-li-swagger.postman_collection.json" --environment="environment.json.postman_environment" --env-var baseUrl=${BACKEND_CONTAINER_NAME}:3000 -n 1 --bail
networks:
  network:
    name: ${NETWORK_NAME}
    external: true
